app = "mazr3a-frontend"
primary_region = "ams"

[build]
  dockerfile = "Dockerfile"
  [build.args]
    VITE_API_BASE_URL = "https://mazr3a-backend.fly.dev"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1
